### ISSUE TITLE
Refusing to clean tmp files

### ISSUE THREAD

**Issue by smirarab** [sate-dev/sate-core#15]
I am getting the following error for all the temporary directories that are being created. 

Refused to clean '/v/filer4b/v20q001/smirarab/.sate/satejob/tempf7_e2G/step0/longest/d1/d1/tempmafft5zR2Cp': not created by SATe.

I am not tampering with the tmp directory. 

And these warnings seem rather harmless. Everything runs fine, except the fact that tmp directories are not removed.

**Comment by mtholder** [comment]
Are there any files in the directory? 

We are trying to get rid of all of the files created by sate and then call rmdir. But rmdir will fail if there are files in the directory. We have a master list of files that SATe creates in the filemgr.py  If we add the names of the "stranded" files to that list, then we should clean things up.  It is possible that this is an order-of-operations bug in which we try to remove the directory (which fails), then we remove the files, but we have already "delisted" the directory from the registry of all directories created by SATé (leading to the error message that you are seeing).

Sorry for the stranding of files. We opted to do this rather than the more dangerous, python equivalent of "rm -r" (the python shutil.rmtree call).

Hopefully, there are just a few files we forgot to list, and we can clear this up quickly.

thanks,
Mark

**Comment by smirarab** [comment]
> Are there any files in the directory?

No, the directories are empty.

Thanks
Siavash

**Comment by joaks1** [comment]
I believe SATe now cleans up after itself (unless the user requests otherwise).  If problems with removing of temp files crop up again, please re-open.
