### ISSUE TITLE
Sequences appear twice in the Alignment output file

### ISSUE THREAD

**Issue by smirarab** [sate-dev/sate-core#5]
For some reason sequences appear twice in my output alignment, one time with the correct sequence name, and other time with everything translated to lower case. So, if I have 50 sequences, I see 100 sequences in the output alignment. 

It seems that the error is just in outputting the alignment because 1- the output tree is fine, 2- the input alignment to the RAxML in final step in the temp directory is fine. 

I will send out example test cases separately (sorry I cannot post my datasets here)!

**Comment by jeetsukumaran** [comment]
Hi Siavash. Thanks for pointing this out. This should be fixed in the latest commit.

**Comment by smirarab** [comment]
Thanks Jeet for the quick reply! 

Just wondering, was the issue just a matter of outputting the final alignments (I think it is but am not quite sure)? 

I have run SATe on some 900 genes and am wondering if simply removing the extra version of each sequence is ok, or I need to rerun the experiments? Thanks!

Siavash

**Comment by jeetsukumaran** [comment]
That is correct. When the data is read in initially, the taxon labels are mapped to a set of "safe" labels that are acceptable to all programs in the pipeline. When the analysis is complete, the original taxon labels are restored. The bug was because the safe labels were not removed from the dictionary, and thus got written out along with the restored sequences.
